2024-06-01 18:51:35,593 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-06-01 18:51:35,593 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Configure stats pid to 347793
2024-06-01 18:51:35,593 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Loading settings from /home/admin1/.config/wandb/settings
2024-06-01 18:51:35,593 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Loading settings from /home/admin1/5703-upload/5703/Transformer_VQA_no/wandb/settings
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_vqa2.py', 'program_abspath': '/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py', 'program': '/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py'}
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:_log_setup():527] Logging user logs to /home/admin1/5703-upload/5703/Transformer_VQA_no/wandb/run-20240601_185135-cuoy6cn9/logs/debug.log
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:_log_setup():528] Logging internal logs to /home/admin1/5703-upload/5703/Transformer_VQA_no/wandb/run-20240601_185135-cuoy6cn9/logs/debug-internal.log
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:init():567] calling init triggers
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {'config': 'config'}
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:init():617] starting backend
2024-06-01 18:51:35,594 INFO    MainThread:347793 [wandb_init.py:init():621] setting up manager
2024-06-01 18:51:35,597 INFO    MainThread:347793 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-01 18:51:35,598 INFO    MainThread:347793 [wandb_init.py:init():629] backend started and connected
2024-06-01 18:51:35,603 INFO    MainThread:347793 [wandb_init.py:init():721] updated telemetry
2024-06-01 18:51:35,603 INFO    MainThread:347793 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-06-01 18:51:36,506 INFO    MainThread:347793 [wandb_run.py:_on_init():2344] communicating current version
2024-06-01 18:51:38,021 WARNING MainThread:347793 [wandb_init.py:init():1209] interrupted
Traceback (most recent call last):
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 803, in init
    run._on_init()
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2348, in _on_init
    version_result = version_handle.wait(timeout=30)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-06-01 18:51:44,566 WARNING MsgRouterThr:347793 [router.py:message_loop():77] message_loop has been closed
