Traceback (most recent call last):
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 389, in <module>
    main(args, config)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 181, in main
    datasets = create_dataset('vqa', config)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/dataset/__init__.py", line 54, in create_dataset
    vqa_test_dataset = vqa_dataset(config['test_file'], test_transform,config['data_root'], split='test', answer_list=config['answer_list'])
KeyError: 'answer_list'
Not using distributed mode
Creating vqa datasets